version: '3.8'

services:
  api:
    build: .
    container_name: imersao-devops-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload